### ISSUE TITLE
Time shown is 0 UTC when my location is -6 UTC 

### ISSUE THREAD

**Issue by vbc4ejyg** [SamuelBolduc/crashplan-logs#2]
Love this script, thanks!

My output time is -6 hours from my local time zone and I would like it to match the crashplan logs (time it actually took place).

Seems like I need to adjust this code somehow?
const parsedDate = moment.utc(`${date} ${time}`, 'MM/DD/YY hh:mma').local();

**Comment by vbc4ejyg** [comment]
Looks like just remove the utc.

const parsedDate = moment.utc(${date} ${time}, 'MM/DD/YY hh:mma').local();
to
const parsedDate = moment(`${date} ${time}`, 'MM/DD/YY hh:mma').local();

**Comment by SamuelBolduc** [comment]
@madfusker did you end up solving the issue? On my end it displays the local time. I'm wondering if on a different OS the logs are different or the `moment` library doesn't get the local timezone right for some reason

**Comment by vbc4ejyg** [comment]
Changing "moment.utc" to just "moment" fixed it and now times are local.  I am not sure why it would be different.  This is on a QNAP TVS-872XT NAS.  I think it's busybox, but I am not sure since it's their own build.

[~] # cat /etc/issue
Welcome to TVS-872XT(192.168.1.10), QNAP Systems, Inc.

[~] # date
Mon Jan  4 14:34:43 CST 2021

Output now:
✔ 2021-01-04 14:35 - ⬆ 4.29 kB in 0 mins /share/docker/appdata/crashplan-pro/xdg/config
✔ 2021-01-04 14:35 - ⬆ 154 kB in 0 mins /share/docker/appdata/crashplan-pro/xdg
